In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [2]:
flights = pd.read_csv(
    r"C:\Users\ACER\Downloads\flights.csv\flights.csv",
    low_memory=False
)

airlines = pd.read_csv(r"C:\Users\ACER\Downloads\airlines.csv")

airports = pd.read_csv(r"C:\Users\ACER\Downloads\airports.csv")

In [3]:
flights_clean = flights.copy()
airlines_clean = airlines.copy()
airports_clean = airports.copy()

In [4]:
flights_clean.isnull().sum()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
TAIL_NUMBER              14721
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           86153
DEPARTURE_DELAY          86153
TAXI_OUT                 89047
WHEELS_OFF               89047
SCHEDULED_TIME               6
ELAPSED_TIME            105071
AIR_TIME                105071
DISTANCE                     0
WHEELS_ON                92513
TAXI_IN                  92513
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME             92513
ARRIVAL_DELAY           105071
DIVERTED                     0
CANCELLED                    0
CANCELLATION_REASON    5729195
AIR_SYSTEM_DELAY       4755640
SECURITY_DELAY         4755640
AIRLINE_DELAY          4755640
LATE_AIRCRAFT_DELAY    4755640
WEATHER_DELAY          4755640
dtype: int64

In [5]:
airlines_clean.isnull().sum()

IATA_CODE    0
AIRLINE      0
dtype: int64

In [6]:
airports_clean.isnull().sum()

IATA_CODE    0
AIRPORT      0
CITY         0
STATE        0
COUNTRY      0
LATITUDE     3
LONGITUDE    3
dtype: int64

In [7]:
missing = flights_clean.isnull().sum()

missing_percentage = (missing / len(flights_clean)) * 100

missing_table = pd.DataFrame({
    "Missing Values": missing,
    "Missing Percentage": missing_percentage
})

missing_table.sort_values(by="Missing Percentage", ascending=False)

                     Missing Values  Missing Percentage
CANCELLATION_REASON         5729195           98.455357
LATE_AIRCRAFT_DELAY         4755640           81.724960
WEATHER_DELAY               4755640           81.724960
AIRLINE_DELAY               4755640           81.724960
AIR_SYSTEM_DELAY            4755640           81.724960
SECURITY_DELAY              4755640           81.724960
ELAPSED_TIME                 105071            1.805629
AIR_TIME                     105071            1.805629
ARRIVAL_DELAY                105071            1.805629
WHEELS_ON                     92513            1.589822
TAXI_IN                       92513            1.589822
ARRIVAL_TIME                  92513            1.589822
WHEELS_OFF                    89047            1.530259
TAXI_OUT                      89047            1.530259
DEPARTURE_TIME                86153            1.480526
DEPARTURE_DELAY               86153            1.480526
TAIL_NUMBER                   14721            0.252978
SCHEDULED_TIME                    6            0.000103
DESTINATION_AIRPORT               0            0.000000
DAY                               0            0.000000
DAY_OF_WEEK                       0            0.000000
AIRLINE                           0            0.000000
FLIGHT_NUMBER                     0            0.000000
MONTH                             0            0.000000
ORIGIN_AIRPORT                    0            0.000000
SCHEDULED_DEPARTURE               0            0.000000
YEAR                              0            0.000000
SCHEDULED_ARRIVAL                 0            0.000000
DISTANCE                          0            0.000000
DIVERTED                          0            0.000000
CANCELLED                         0            0.000000

In [8]:
flights_clean.duplicated().sum()

np.int64(0)

In [9]:
airlines_clean.duplicated().sum()

np.int64(0)

In [10]:
airports_clean.duplicated().sum()

np.int64(0)

In [11]:
flights_clean = flights_clean.drop_duplicates()

In [12]:
flights_clean.dtypes

YEAR                     int64
MONTH                    int64
DAY                      int64
DAY_OF_WEEK              int64
AIRLINE                    str
FLIGHT_NUMBER            int64
TAIL_NUMBER                str
ORIGIN_AIRPORT             str
DESTINATION_AIRPORT        str
SCHEDULED_DEPARTURE      int64
DEPARTURE_TIME         float64
DEPARTURE_DELAY        float64
TAXI_OUT               float64
WHEELS_OFF             float64
SCHEDULED_TIME         float64
ELAPSED_TIME           float64
AIR_TIME               float64
DISTANCE                 int64
WHEELS_ON              float64
TAXI_IN                float64
SCHEDULED_ARRIVAL        int64
ARRIVAL_TIME           float64
ARRIVAL_DELAY          float64
DIVERTED                 int64
CANCELLED                int64
CANCELLATION_REASON        str
AIR_SYSTEM_DELAY       float64
SECURITY_DELAY         float64
AIRLINE_DELAY          float64
LATE_AIRCRAFT_DELAY    float64
WEATHER_DELAY          float64
dtype: object

In [13]:
flights_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 31 columns):
 #   Column               Dtype
---  ------               -----
 0   YEAR                 int64
 1   MONTH                int64
 2   DAY                  int64
 3   DAY_OF_WEEK          int64
 4   AIRLINE              str
 5   FLIGHT_NUMBER        int64
 6   TAIL_NUMBER          str
 7   ORIGIN_AIRPORT       str
 8   DESTINATION_AIRPORT  str
 9   SCHEDULED_DEPARTURE  int64
 10  DEPARTURE_TIME       float64
 11  DEPARTURE_DELAY      float64
 12  TAXI_OUT             float64
 13  WHEELS_OFF           float64
 14  SCHEDULED_TIME       float64
 15  ELAPSED_TIME         float64
 16  AIR_TIME             float64
 17  DISTANCE             int64
 18  WHEELS_ON            float64
 19  TAXI_IN              float64
 20  SCHEDULED_ARRIVAL    int64
 21  ARRIVAL_TIME         float64
 22  ARRIVAL_DELAY        float64
 23  DIVERTED             int64
 24  CANCELLED            int64
 25  CANCELLATION_REASON  str
 26  AIR_SYSTEM_DELAY     float64
 27  SECURITY_DELAY       float64
 28  AIRLINE_DELAY        float64
 29  LATE_AIRCRAFT_DELAY  float64
 30  WEATHER_DELAY        float64
dtypes: float64(16), int64(10), str(5)
memory usage: 1.3 GB

In [14]:
flights_clean.columns = flights_clean.columns.str.lower()
airlines_clean.columns = airlines_clean.columns.str.lower()
airports_clean.columns = airports_clean.columns.str.lower()

In [16]:
for col in flights_clean.select_dtypes(include=['object', 'string']).columns:
    flights_clean[col] = flights_clean[col].str.strip()

In [17]:
for col in airlines_clean.select_dtypes(include=['object', 'string']).columns:
    airlines_clean[col] = airlines_clean[col].str.strip()

for col in airports_clean.select_dtypes(include=['object', 'string']).columns:
    airports_clean[col] = airports_clean[col].str.strip()

In [18]:
flights_clean["airline"] = flights_clean["airline"].str.upper()

flights_clean["origin_airport"] = flights_clean["origin_airport"].str.upper()

flights_clean["destination_airport"] = flights_clean["destination_airport"].str.upper()

In [19]:
flights_clean["airline"].unique()

<StringArray>
['AS', 'AA', 'US', 'DL', 'NK', 'UA', 'HA', 'B6', 'OO', 'EV', 'MQ', 'F9', 'WN',
 'VX']
Length: 14, dtype: str

In [20]:
flights_clean["origin_airport"].unique()

<StringArray>
[  'ANC',   'LAX',   'SFO',   'SEA',   'LAS',   'DEN',   'SLC',   'PDX',
   'FAI',   'MSP',
 ...
 '13964', '13541', '15027', '10170', '10165', '15497', '12265', '14222',
 '14025', '13502']
Length: 628, dtype: str

In [21]:
flights_clean.describe()

,year,month,day,day_of_week,flight_number,scheduled_departure,departure_time,departure_delay,taxi_out,wheels_off,scheduled_time,elapsed_time,air_time,distance,wheels_on,taxi_in,scheduled_arrival,arrival_time,arrival_delay,diverted,cancelled,air_system_delay,security_delay,airline_delay,late_aircraft_delay,weather_delay
count,5819079.0,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.732926e+06,5.732926e+06,5.730032e+06,5.730032e+06,5.819073e+06,5.714008e+06,5.714008e+06,5.819079e+06,5.726566e+06,5.726566e+06,5.819079e+06,5.726566e+06,5.714008e+06,5.819079e+06,5.819079e+06,1.063439e+06,1.063439e+06,1.063439e+06,1.063439e+06,1.063439e+06
mean,2015.0,6.524085e+00,1.570459e+01,3.926941e+00,2.173093e+03,1.329602e+03,1.335204e+03,9.370158e+00,1.607166e+01,1.357171e+03,1.416859e+02,1.370062e+02,1.135116e+02,8.223565e+02,1.471469e+03,7.434971e+00,1.493808e+03,1.476491e+03,4.407057e+00,2.609863e-03,1.544643e-02,1.348057e+01,7.615387e-02,1.896955e+01,2.347284e+01,2.915290e+00
std,0.0,3.405137e+00,8.783425e+00,1.988845e+00,1.757064e+03,4.837518e+02,4.964233e+02,3.708094e+01,8.895574e+00,4.980094e+02,7.521058e+01,7.421107e+01,7.223082e+01,6.077843e+02,5.221879e+02,5.638548e+00,5.071647e+02,5.263197e+02,3.927130e+01,5.102012e-02,1.233201e-01,2.800368e+01,2.143460e+00,4.816164e+01,4.319702e+01,2.043334e+01
min,2015.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-8.200000e+01,1.000000e+00,1.000000e+00,1.800000e+01,1.400000e+01,7.000000e+00,2.100000e+01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-8.700000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2015.0,4.000000e+00,8.000000e+00,2.000000e+00,7.300000e+02,9.170000e+02,9.210000e+02,-5.000000e+00,1.100000e+01,9.350000e+02,8.500000e+01,8.200000e+01,6.000000e+01,3.730000e+02,1.054000e+03,4.000000e+00,1.110000e+03,1.059000e+03,-1.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2015.0,7.000000e+00,1.600000e+01,4.000000e+00,1.690000e+03,1.325000e+03,1.330000e+03,-2.000000e+00,1.400000e+01,1.343000e+03,1.230000e+02,1.180000e+02,9.400000e+01,6.470000e+02,1.509000e+03,6.000000e+00,1.520000e+03,1.512000e+03,-5.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,3.000000e+00,0.000000e+00
75%,2015.0,9.000000e+00,2.300000e+01,6.000000e+00,3.230000e+03,1.730000e+03,1.740000e+03,7.000000e+00,1.900000e+01,1.754000e+03,1.730000e+02,1.680000e+02,1.440000e+02,1.062000e+03,1.911000e+03,9.000000e+00,1.918000e+03,1.917000e+03,8.000000e+00,0.000000e+00,0.000000e+00,1.800000e+01,0.000000e+00,1.900000e+01,2.900000e+01,0.000000e+00
max,2015.0,1.200000e+01,3.100000e+01,7.000000e+00,9.855000e+03,2.359000e+03,2.400000e+03,1.988000e+03,2.250000e+02,2.400000e+03,7.180000e+02,7.660000e+02,6.900000e+02,4.983000e+03,2.400000e+03,2.480000e+02,2.400000e+03,2.400000e+03,1.971000e+03,1.000000e+00,1.000000e+00,1.134000e+03,5.730000e+02,1.971000e+03,1.331000e+03,1.211000e+03

In [22]:
flights_clean.insert(0, "flight_id", range(1, len(flights_clean) + 1))

In [23]:
set(flights_clean["airline"]) - set(airlines_clean["airline"])

{'AA',
 'AS',
 'B6',
 'DL',
 'EV',
 'F9',
 'HA',
 'MQ',
 'NK',
 'OO',
 'UA',
 'US',
 'VX',
 'WN'}

In [24]:
set(flights_clean["origin_airport"]) - set(airports_clean["iata_code"])

{'10135',
 '10136',
 '10140',
 '10141',
 '10146',
 '10154',
 '10155',
 '10157',
 '10158',
 '10165',
 '10170',
 '10185',
 '10208',
 '10257',
 '10268',
 '10279',
 '10299',
 '10333',
 '10372',
 '10397',
 '10408',
 '10423',
 '10431',
 '10434',
 '10469',
 '10529',
 '10551',
 '10561',
 '10577',
 '10581',
 '10599',
 '10620',
 '10627',
 '10631',
 '10685',
 '10693',
 '10713',
 '10721',
 '10728',
 '10731',
 '10732',
 '10739',
 '10747',
 '10754',
 '10779',
 '10781',
 '10785',
 '10792',
 '10800',
 '10821',
 '10849',
 '10868',
 '10874',
 '10918',
 '10926',
 '10980',
 '10990',
 '10994',
 '11003',
 '11013',
 '11042',
 '11049',
 '11057',
 '11066',
 '11067',
 '11076',
 '11097',
 '11109',
 '11111',
 '11122',
 '11140',
 '11146',
 '11150',
 '11193',
 '11203',
 '11252',
 '11259',
 '11267',
 '11274',
 '11278',
 '11292',
 '11298',
 '11308',
 '11315',
 '11337',
 '11413',
 '11423',
 '11433',
 '11447',
 '11471',
 '11481',
 '11503',
 '11525',
 '11537',
 '11540',
 '11577',
 '11587',
 '11603',
 '11612',
 '11617',
 '11618',
 '11624',
 '11630',
 '11637',
 '11638',
 '11641',
 '11648',
 '11695',
 '11697',
 '11721',
 '11775',
 '11778',
 '11823',
 '11865',
 '11867',
 '11884',
 '11898',
 '11905',
 '11921',
 '11953',
 '11973',
 '11977',
 '11980',
 '11982',
 '11986',
 '11995',
 '11996',
 '12003',
 '12007',
 '12016',
 '12094',
 '12129',
 '12156',
 '12173',
 '12177',
 '12191',
 '12197',
 '12206',
 '12217',
 '12255',
 '12264',
 '12265',
 '12266',
 '12278',
 '12280',
 '12323',
 '12335',
 '12339',
 '12343',
 '12389',
 '12391',
 '12402',
 '12441',
 '12448',
 '12451',
 '12478',
 '12511',
 '12519',
 '12523',
 '12758',
 '12819',
 '12884',
 '12888',
 '12889',
 '12891',
 '12892',
 '12896',
 '12898',
 '12915',
 '12945',
 '12951',
 '12953',
 '12954',
 '12982',
 '12992',
 '13029',
 '13061',
 '13076',
 '13127',
 '13158',
 '13184',
 '13198',
 '13204',
 '13230',
 '13232',
 '13241',
 '13244',
 '13256',
 '13264',
 '13277',
 '13290',
 '13296',
 '13303',
 '13342',
 '13344',
 '13360',
 '13367',
 '13377',
 '13422',
 '13433',
 '13459',
 '13476',
 '13485',
 '13486',
 '13487',
 '13495',
 '13502',
 '13541',
 '13577',
 '13795',
 '13796',
 '13830',
 '13851',
 '13871',
 '13873',
 '13891',
 '13930',
 '13931',
 '13933',
 '13964',
 '13970',
 '14006',
 '14025',
 '14027',
 '14057',
 '14098',
 '14100',
 '14107',
 '14108',
 '14109',
 '14113',
 '14122',
 '14150',
 '14193',
 '14222',
 '14252',
 '14254',
 '14256',
 '14262',
 '14307',
 '14321',
 '14457',
 '14487',
 '14489',
 '14492',
 '14520',
 '14524',
 '14543',
 '14570',
 '14574',
 '14576',
 '14588',
 '14633',
 '14635',
 '14674',
 '14679',
 '14683',
 '14685',
 '14689',
 '14696',
 '14698',
 '14709',
 '14711',
 '14730',
 '14747',
 '14771',
 '14783',
 '14794',
 '14814',
 '14828',
 '14831',
 '14842',
 '14843',
 '14869',
 '14893',
 '14905',
 '14908',
 '14952',
 '14960',
 '14986',
 '15016',
 '15024',
 '15027',
 '15041',
 '15048',
 '15070',
 '15096',
 '15249',
 '15295',
 '15304',
 '15323',
 '15356',
 '15370',
 '15376',
 '15380',
 '15389',
 '15401',
 '15411',
 '15412',
 '15497',
 '15607',
 '15624',
 '15841',
 '15919',
 '15991',
 '16218'}

In [25]:
set(flights_clean["destination_airport"]) - set(airports_clean["iata_code"])

{'10135',
 '10136',
 '10140',
 '10141',
 '10146',
 '10154',
 '10155',
 '10157',
 '10158',
 '10165',
 '10170',
 '10185',
 '10208',
 '10257',
 '10268',
 '10279',
 '10299',
 '10333',
 '10372',
 '10397',
 '10408',
 '10423',
 '10431',
 '10434',
 '10469',
 '10529',
 '10551',
 '10561',
 '10577',
 '10581',
 '10599',
 '10620',
 '10627',
 '10631',
 '10666',
 '10685',
 '10693',
 '10713',
 '10721',
 '10728',
 '10731',
 '10732',
 '10739',
 '10747',
 '10754',
 '10779',
 '10781',
 '10785',
 '10792',
 '10800',
 '10821',
 '10849',
 '10868',
 '10874',
 '10918',
 '10926',
 '10980',
 '10990',
 '10994',
 '11003',
 '11013',
 '11042',
 '11049',
 '11057',
 '11066',
 '11067',
 '11076',
 '11097',
 '11109',
 '11111',
 '11122',
 '11140',
 '11146',
 '11150',
 '11193',
 '11203',
 '11252',
 '11259',
 '11267',
 '11274',
 '11278',
 '11292',
 '11298',
 '11308',
 '11315',
 '11337',
 '11413',
 '11423',
 '11433',
 '11447',
 '11471',
 '11481',
 '11503',
 '11525',
 '11537',
 '11540',
 '11577',
 '11587',
 '11603',
 '11612',
 '11617',
 '11618',
 '11624',
 '11630',
 '11637',
 '11638',
 '11641',
 '11648',
 '11695',
 '11697',
 '11721',
 '11775',
 '11778',
 '11823',
 '11865',
 '11867',
 '11884',
 '11898',
 '11905',
 '11921',
 '11953',
 '11973',
 '11977',
 '11980',
 '11982',
 '11986',
 '11995',
 '11996',
 '12003',
 '12007',
 '12016',
 '12094',
 '12129',
 '12156',
 '12173',
 '12177',
 '12191',
 '12197',
 '12206',
 '12217',
 '12255',
 '12264',
 '12265',
 '12266',
 '12278',
 '12280',
 '12323',
 '12335',
 '12339',
 '12343',
 '12389',
 '12391',
 '12402',
 '12441',
 '12448',
 '12451',
 '12478',
 '12511',
 '12519',
 '12523',
 '12758',
 '12819',
 '12884',
 '12888',
 '12889',
 '12891',
 '12892',
 '12896',
 '12898',
 '12915',
 '12945',
 '12951',
 '12953',
 '12954',
 '12982',
 '12992',
 '13029',
 '13061',
 '13076',
 '13127',
 '13158',
 '13184',
 '13198',
 '13204',
 '13230',
 '13232',
 '13241',
 '13244',
 '13256',
 '13264',
 '13277',
 '13290',
 '13296',
 '13303',
 '13342',
 '13344',
 '13360',
 '13367',
 '13377',
 '13422',
 '13433',
 '13459',
 '13476',
 '13485',
 '13486',
 '13487',
 '13495',
 '13502',
 '13541',
 '13577',
 '13795',
 '13796',
 '13830',
 '13851',
 '13871',
 '13873',
 '13891',
 '13930',
 '13931',
 '13933',
 '13964',
 '13970',
 '14006',
 '14025',
 '14027',
 '14057',
 '14098',
 '14100',
 '14107',
 '14108',
 '14109',
 '14113',
 '14122',
 '14150',
 '14193',
 '14222',
 '14252',
 '14254',
 '14256',
 '14262',
 '14307',
 '14321',
 '14457',
 '14487',
 '14489',
 '14492',
 '14520',
 '14524',
 '14543',
 '14570',
 '14574',
 '14576',
 '14588',
 '14633',
 '14635',
 '14674',
 '14679',
 '14683',
 '14685',
 '14689',
 '14696',
 '14698',
 '14709',
 '14711',
 '14730',
 '14747',
 '14771',
 '14783',
 '14794',
 '14814',
 '14828',
 '14831',
 '14842',
 '14843',
 '14869',
 '14893',
 '14905',
 '14908',
 '14952',
 '14960',
 '14986',
 '15016',
 '15024',
 '15027',
 '15041',
 '15048',
 '15070',
 '15096',
 '15249',
 '15295',
 '15304',
 '15323',
 '15356',
 '15370',
 '15376',
 '15380',
 '15389',
 '15401',
 '15411',
 '15412',
 '15497',
 '15607',
 '15624',
 '15841',
 '15919',
 '15991',
 '16218'}

In [26]:
set()

set()

In [28]:
import os

In [29]:
os.makedirs("Dataset/Cleaned", exist_ok=True)

In [30]:
flights_clean.to_csv("Dataset/Cleaned/clean_flights.csv", index=False)

airlines_clean.to_csv("Dataset/Cleaned/clean_airlines.csv", index=False)

airports_clean.to_csv("Dataset/Cleaned/clean_airports.csv", index=False)

In [32]:
airlines_clean.to_csv("Dataset/Cleaned/clean_airlines.csv", index=False)

airports_clean.to_csv("Dataset/Cleaned/clean_airports.csv", index=False)